%function guiProgramowe
function guiTrajektoria_A

% f = figure('Name','guiTrajektoria_A',...
% 'Position',[650,350,500,400]);
f = figure('Name','guiTrajektoria_A',...
'Position',[350,150,500,400],'MenuBar','none','NumberTitle','off');

osie = axes('Units','pixels','Position',[50,80,250,250], ...
'xlim',[0 10], 'ylim',[0 10]);
osie.XLabel.String = 'Dystans [m]';
osie.YLabel.String = 'Wysokoœæ [m]';
osie.Title.String = 'Trajektoria pi³ki';

textPredk = uicontrol('Style','text',...
'String','Prêdkoœæ pocz¹tkowa [m/s]',...
'Position',[330,300,150,20]);
velocityBox = uicontrol('Style','edit',...
'String','5',...
'Tag','velocityBox',...
'Position',[363,270,80,20]);
textKat = uicontrol('Style','text',...
'String','K¹t wyrzutu [stopnie]',...
'Position',[330,200,150,20]);
angleBox = uicontrol('Style','edit',...
'String','45',...
'Tag','angleBox',...
'Position',[363,170,80,20]);
thrawPush = uicontrol('Style','pushbutton',...
'String','Rzut',...
'Tag','thrawPush',...
'Position',[363,90,80,20],...
'Callback',@pushbuttonCallback);

end

function pushbuttonCallback(source,~)

g = 9.81;
velObj = findobj('Tag','velocityBox');
v0 = str2double(velObj.String);
angleObj = findobj('Tag','angleBox');
theta = str2double(angleObj.String)*pi/180;
t1 = 2*v0*sin(theta)/g;
t=0:0.01:t1;
x = v0*cos(theta)*t;
y = v0*sin(theta)*t - g*t.^2/2;

hold on
comet(x,y)

end